"""updating users table with date

Revision ID: 51b5330cb60d
Revises: 3e0edbbf03d9
Create Date: 2023-03-28 15:06:28.360134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b5330cb60d'
down_revision = '3e0edbbf03d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_posted', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_posted')
    # ### end Alembic commands ###
